Repository Apoorv-cloud/2_Hacktoberfest-22, pull requests merged in 2022-10, with the labels that each got.

#1 Apoorv's Detail Added
  images/Apoorv.jpg
  index.html
Labels: hacktoberfest-accepted

#4 Added Portfolio
  images/Aaron.jpg
  index.html
Labels: hacktoberfest-accepted

#5 Card Added
  .DS_Store
  images/.DS_Store
  images/Ashutosh.png
  index.html
Labels: hacktoberfest-accepted

#15 pic
  images/Astha.jpg
Labels: hacktoberfest-accepted

#16 done
  abhinav.jpg
  index.html
Labels: hacktoberfest-accepted

#20 New Profile Added
  images/Esha.jpg
  index.html
Labels: hacktoberfest-accepted

#19 Code branch
  images/AadarshPandey.jpeg
  index.html
Labels: hacktoberfest-accepted

#24 Update index.html
  index.html
Labels: hacktoberfest-accepted

#23 cards
  images/Anushka.jpeg
  index.html
Labels: hacktoberfest-accepted

#25 added new card Rohan
  index.html
Labels: hacktoberfest-accepted

#26 card added with asset image
  images/Harsh_tripathi.jpg
  index.html
Labels: hacktoberfest-accepted

#28 added photo rohan
  images/rohan.png
Labels: hacktoberfest-accepted

#29 added photo to card(rohan)
  index.html
Labels: hacktoberfest-accepted

#30 Update index.html
  index.html
Labels: hacktoberfest-accepted

#32 Anuj Card
  images/anuj.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#34 styling
  back.jpg
  back.png
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest'22

#43 URL FIXES !
  images/.DS_Store
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#39 Portfolio Update
  images/Mansi Nijhawan.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#40 Add files via upload
  images/Shashank_Image.jpeg
Labels: hacktoberfest-accepted, hacktoberfest'22

#41 Update index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#46 Added Prabal Tripathi
  images/Prabal Tripathi.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#50 Minor changes
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#49 My Folio added
  images/Ushma_Gupta.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#51 Updated index.html
  images/Hira Amir.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#52 Image added
  images/UtkarshSingh.jpeg
Labels: hacktoberfest-accepted, hacktoberfest'22

#53 Kartikey's Profile
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#55 Update index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#57 Update index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#59 Update
  images/.DS_Store
  images/Yash.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#60 Deepak's card added
  images/DeepakJain.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#61 added profile
  images/Keshav.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#64 myinformation
  images/Aniket_Mishra.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#65 Profile added
  .vscode/settings.json
  images/Dhruv_Kushwaha.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#66 Second PR - Minor Change
  .vscode/settings.json
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#67 i have added my a profile photo and links to my linkedin and github
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#68 I have add my profile photo and link to my github and linkedin
  index.html
  style.css
Labels: hacktoberfest-accepted, hacktoberfest'22

#69 utkarsh-profile-added
  images/Utkarsh Khokhar.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#72 Jatin branch2 details
  images/jatin-img.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest'22

#74 update index.html
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#75 update style.css
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#76 card added
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#78 added profile
  images/simranyadav.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#79 four
  images/Jaswant.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#83 2nd commit - Card Added
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#87 linkdin profile added
  images/prajjwal.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#89 Created Lisha's Card
  images/Lisha.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#91 Image Added
  images/GracyGupta.jpg
Labels: hacktoberfest-accepted, hacktoberfest

#92 Gracy card
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#93 added my portfolio
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#94 Profiles Added
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#99 Samratakgec3
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#100 Name added
  images/samriddhi.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#102 added the target to the anchor tag so that urls open at the new tab
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#103 profile id
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#104 Added Deepak's second card
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#105 details file
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#106 increased radius
  style.css
Labels: hacktoberfest-accepted, hacktoberfest

#108 image
  images/himanshu.jpeg
Labels: hacktoberfest-accepted, hacktoberfest

#111 New Commit
  images/ayushi.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#116 place card
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#117 image
  images/mona.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#114 Added Prabal Tripathi
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#115 Added Utkarsh's profile details
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#118 harsh saxena added potfolio
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#119 Aditya card
  images/aditya.png
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#122 harsh saxena added portfolio after syncing
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#123 updated about me section
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#128 Second change done in card
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#129 Added my profile
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#130 Tanvi: card added
  images/tanvi-srivastava.jpeg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest

#131 Card added
  images/Love_Agarwal.jpg
  index.html
Labels: hacktoberfest-accepted, hacktoberfest
